columns_to_drop:
  - Sub Frame
  - MidSterDown_X
  - MidSterDown_Y
  - MidSterDown_Z

marker_loc:
  r_foot:
    - [13, 12]
    - [13, 11]
    - [12, 14]
    - [11, 14]
    - [11, 10]
    - [12, 10]
    - [13, 14]
    - [14, 10]
    - [8, 9]
    - [9, 10]
    - [10, 13]
    - [11, 8]
    - [12, 8]
  r_leg:
    - [6, 7]
    - [4, 5]
    - [6, 4]
    - [6, 5]
    - [7, 4]
    - [7, 5]
  hip:
    - [0, 3]
    - [3, 2]
    - [2, 1]
    - [0, 2]
    - [3, 1]
    - [0, 1]
  l_foot:
    - [24, 23]
    - [24, 22]
    - [23, 25]
    - [22, 25]
    - [22, 21]
    - [23, 21]
    - [24, 25]
    - [25, 21]
    - [19, 20]
    - [21, 22]
    - [24, 21]
    - [20, 21]
    - [22, 19]
    - [23, 19]
  l_leg:
    - [17, 18]
    - [15, 17]
    - [16, 17]
    - [15, 16]
    - [18, 15]
    - [18, 16]
  torso:
    - [27, 26]
    - [27, 28]
    - [26, 28]
  l_arm:
    - [33, 34]
    - [34, 35]
    - [35, 28]
  r_arm:
    - [32, 31]
    - [31, 30]
    - [30, 29]
    - [32, 26]

default_preprocessing:
  interpolating:      true
  smoothing:          true
  position_centering: true
  mean_value_centering: true
  z-score_normalization: false

logging:
  version: 1
  disable_existing_loggers: false

  formatters:
    standard:
      format: "%(asctime)s | %(name)s | %(levelname)s | [%(subject_id)s] | %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      level: INFO
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: standard
      level: DEBUG
      filename: logs/processor_log.log
      #mode: w
      maxBytes: 10000000
      backupCount: 5

  root:
    handlers:
      - console
      - file
    level: DEBUG